---

new_interfaces:
  - name: Ethernet1/43
    enabled: true
    mtu: '9216'
  - name: Ethernet1/44
    enabled: true
    mtu: '9216'
  - name: Ethernet1/49
    enabled: true
    mtu: '9216'
  - name: Ethernet1/50
    enabled: true
    mtu: '9216'
  - name: Ethernet1/51
    enabled: true
    mtu: '9216'
  - name: Ethernet1/52
    enabled: true
    mtu: '9216'
  - name: mgmt0
    description: Management Interface
    enabled: true
  - name: Loopack0
    description: Router ID
    enabled: true
  - name: Vlan100
    description: Tunnel Endpoint
    enabled: true
    mtu: '9216'
  - name: Vlan200
    description: vSphere Management
    enabled: true
    mtu: '9216'
  - name: Vlan300
    description: Storage Replication
    enabled: true
    mtu: '9216'
  - name: Vlan400
    description: vMotion - Live Migration
    enabled: true
    mtu: '9216'
  - name: port-channel100
    description: vPC Peer-Link
    enabled: true
    mode: layer2
    mtu: '9216'

bfd_interfaces:
  - name: Ethernet1/43
    bfd: enable
    echo: enable
  - name: Ethernet1/44
    bfd: enable
    echo: enable
  - name: Ethernet1/47
    bfd: enable
    echo: enable
  - name: Ethernet1/48
    bfd: enable
    echo: enable
  - name: Ethernet1/49
    bfd: enable
    echo: enable
  - name: Ethernet1/50
    bfd: enable
    echo: enable
  - name: Ethernet1/51
    bfd: enable
    echo: enable
  - name: Ethernet1/52
    bfd: enable
    echo: enable
  - name: port-channel100
    bfd: enable
    echo: enable

features:
  - lldp
  - scp-server
  - ospf
  - bfd
  - vpc
  - interface-vlan
  - hsrp
  - lacp

snmp_traps:
  - bfd
  - lldp
  - ospf
  - system
  - upgrade
  - hsrp